# See https://pre-commit.com for more information

# Global exclude list, can be extended for individual hooks
exclude: |
  (?x)^(
    src/WonderlandEngineExternal/.*|
    package/windows/nsis_plugins/.*|
    js/components/.*|
    js/lib/.*|
    js/editor-components-bundle\.js(\.map)?
  )$

default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        # We format json and project files without a newline
        exclude: ^.*\.(json|wlp)$
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
        # Blender OpenGEX exporter uses tabs
        exclude: ^(.*\.ogex|\.gitmodules)$
        args: [--whitespaces-count=4]
  - repo: https://github.com/pezcode/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: limit-blank-lines
        # Don't check free-form text and license files
        exclude: ^(.*\.txt|(.+/)?LICENSE)$
        # Two blank lines are common in Python scripts:
        # https://peps.python.org/pep-0008/#blank-lines
        exclude_types: [python]
  # Download updated dictionary for codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        name: Check spelling
        exclude: |
          (?x)^(
            .*/package-lock\.json|
            doc/m\.css/.*|
            doc/css/.*
          )$
