name: Build
on: [push]

permissions:
  pages: write
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Package
      run: |
        npm ci
        npm run build
        cd example
        /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project ./SpatialAudioLab.wlp --credentials "$WLE_CREDENTIALS"
        cd ..
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: test
      run: |
        export CHROME_PATH="$(which google-chrome)"
        echo "CHROME_PATH=$CHROME_PATH" >> $GITHUB_ENV
        npm install
        npm run watch
    - name: Gzip
      run: gzip -k ./example/deploy/*.*
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./example/deploy


  deploy-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: package
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
