on: [push]

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: |
        npm i
        cd example
        /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project ./SpatialAudioLab.wlp --credentials "$WLE_CREDENTIALS"
        cd ..
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Gzip
      run: gzip -k ./example/deploy/*.*
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./example/deploy

  deploy-pages:
    needs: package
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
